// !请不要手动修改该文件及该目录下的内容，该目录内容皆通过 'npm run genComponents' 命令创建.
type ComponentsImporter = {
    [x: string]: Function
}

const componentsImporter: ComponentsImporter = {
    base: () => import('./Base'),
	affix: () => import('./Affix'),
	anchor: () => import('./Anchor'),
	autoComplete: () => import('./AutoComplete'),
	alert: () => import('./Alert'),
	avatar: () => import('./Avatar'),
	backTop: () => import('./BackTop'),
	badge: () => import('./Badge'),
	breadcrumb: () => import('./Breadcrumb'),
	button: () => import('./Button'),
	calendar: () => import('./Calendar'),
	card: () => import('./Card'),
	collapse: () => import('./Collapse'),
	carousel: () => import('./Carousel'),
	cascader: () => import('./Cascader'),
	checkbox: () => import('./Checkbox'),
	col: () => import('./Col'),
	datePicker: () => import('./DatePicker'),
	divider: () => import('./Divider'),
	dropdown: () => import('./Dropdown'),
	form: () => import('./Form'),
	formModel: () => import('./FormModel'),
	icon: () => import('./Icon'),
	input: () => import('./Input'),
	inputNumber: () => import('./InputNumber'),
	layout: () => import('./Layout'),
	list: () => import('./List'),
	localeProvider: () => import('./LocaleProvider'),
	menu: () => import('./Menu'),
	mentions: () => import('./Mentions'),
	modal: () => import('./Modal'),
	pagination: () => import('./Pagination'),
	popconfirm: () => import('./Popconfirm'),
	popover: () => import('./Popover'),
	progress: () => import('./Progress'),
	radio: () => import('./Radio'),
	rate: () => import('./Rate'),
	row: () => import('./Row'),
	select: () => import('./Select'),
	slider: () => import('./Slider'),
	spin: () => import('./Spin'),
	statistic: () => import('./Statistic'),
	steps: () => import('./Steps'),
	switch: () => import('./Switch'),
	table: () => import('./Table'),
	transfer: () => import('./Transfer'),
	tree: () => import('./Tree'),
	treeSelect: () => import('./TreeSelect'),
	tabs: () => import('./Tabs'),
	tag: () => import('./Tag'),
	timePicker: () => import('./TimePicker'),
	timeline: () => import('./Timeline'),
	tooltip: () => import('./Tooltip'),
	upload: () => import('./Upload'),
	drawer: () => import('./Drawer'),
	skeleton: () => import('./Skeleton'),
	comment: () => import('./Comment'),
	configProvider: () => import('./ConfigProvider'),
	empty: () => import('./Empty'),
	result: () => import('./Result'),
	descriptions: () => import('./Descriptions'),
	pageHeader: () => import('./PageHeader'),
	space: () => import('./Space'),
}

export default componentsImporter;
